# Generated by Django 4.2.9 on 2024-01-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('date_evenement', models.DateField()),
                ('adresse_evenement', models.CharField(max_length=100)),
                ('ville_evenement', models.CharField(max_length=100)),
                ('code_postal_evenement', models.IntegerField()),
                ('numero_telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
