# Generated by Django 4.2.9 on 2024-02-03 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mur_floral', models.BooleanField(default=False)),
                ('phonebooth', models.BooleanField(default=False)),
                ('magnets', models.IntegerField(blank=True, null=True)),
                ('livraison', models.BooleanField(default=False)),
                ('duree', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photobooth', models.BooleanField(default=False)),
                ('miroirbooth', models.BooleanField(default=False)),
                ('videobooth', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='service_details',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Initied', 'Initied'), ('Send', 'Send'), ('OK', 'OK'), ('Prio', 'Prio'), ('Refused', 'Refused')], default='Initied', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceDetails',
        ),
        migrations.AddField(
            model_name='event',
            name='event_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.eventoption'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.eventproduct'),
        ),
    ]
