# Generated by Django 4.2.9 on 2024-02-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoption',
            old_name='livreor',
            new_name='LivreOr',
        ),
        migrations.RenameField(
            model_name='eventoption',
            old_name='livreor_reduc_prix',
            new_name='LivreOr_reduc_prix',
        ),
        migrations.RenameField(
            model_name='eventoption',
            old_name='mur_floral',
            new_name='MurFloral',
        ),
        migrations.RenameField(
            model_name='eventoption',
            old_name='mur_floral_reduc_prix',
            new_name='MurFloral_reduc_prix',
        ),
        migrations.RenameField(
            model_name='eventoption',
            old_name='phonebooth',
            new_name='Phonebooth',
        ),
        migrations.RenameField(
            model_name='eventoption',
            old_name='phonebooth_reduc_prix',
            new_name='Phonebooth_reduc_prix',
        ),
        migrations.AddField(
            model_name='eventoption',
            name='Fond360',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='Fond360_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='Holo3D',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='Holo3D_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='PanneauBienvenue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='PanneauBienvenue_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
