# Generated by Django 4.2.9 on 2024-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eventoption_panneaubienvenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
