# Generated by Django 4.2.9 on 2024-02-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_raison_sociale_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
    ]
