# Generated by Django 4.2.9 on 2024-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_client_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoption',
            name='livreor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='livreor_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Initied', 'Initied'), ('Calculed', 'Calculed'), ('Sended', 'Sended'), ('OK', 'OK'), ('Refused', 'Refused')], default='Initied', max_length=255, null=True),
        ),
    ]
