# Generated by Django 4.2.9 on 2024-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eventdetails_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='horaire',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
