# Generated by Django 4.2.9 on 2024-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoption',
            name='livreor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='livreor_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
