# Generated by Django 4.2.9 on 2024-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_eventdetails_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='url_modele',
            field=models.URLField(null=True),
        ),
    ]
