# Generated by Django 4.2.9 on 2024-04-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_eventdetails_url_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id_card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='comment_client',
            field=models.TextField(null=True),
        ),
    ]
