# Generated by Django 4.2.9 on 2024-02-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_eventoption_magnets_reduc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoption',
            old_name='magnets_reduc',
            new_name='magnets_prix',
        ),
        migrations.RemoveField(
            model_name='eventoption',
            name='mur_floral_reduc',
        ),
        migrations.RemoveField(
            model_name='eventoption',
            name='phonebooth_reduc',
        ),
        migrations.AddField(
            model_name='eventoption',
            name='mur_floral_prix',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='phonebooth_prix',
            field=models.IntegerField(default=False),
        ),
    ]
