# Generated by Django 4.2.9 on 2024-02-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_magnets_reduc_eventoption_magnets_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoption',
            old_name='magnets_prix',
            new_name='magnets_reduc_prix',
        ),
        migrations.RenameField(
            model_name='eventoption',
            old_name='mur_floral_prix',
            new_name='mur_floral_reduc_prix',
        ),
        migrations.RenameField(
            model_name='eventoption',
            old_name='phonebooth_prix',
            new_name='phonebooth_reduc_prix',
        ),
    ]
