# Generated by Django 4.2.9 on 2024-04-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_id_card_eventdetails_comment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_devis',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
