# Generated by Django 4.2.9 on 2024-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_magnets_prix_eventoption_magnets_reduc_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoption',
            name='mur_floral_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventoption',
            name='phonebooth_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
