# Generated by Django 4.2.9 on 2024-02-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_eventoption_mur_floral_reduc_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoption',
            name='magnets_reduc_prix',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
