DATABASES:
    default:
        ENGINE: 'django.db.backends.mysql'
        NAME: 'reservation'
        USER: 'root'
        PASSWORD: 'root'
        HOST: '127.0.0.1'
        PORT: '3306'

SECRET_KEY: 'django-insecure-u(a5+2ib4!mp+g^7lvgra519(1hsaz-+xv$70o8fl3*bpj&^u5'

key: '29e7594c82a72b2ee23f23926ad2308a'
token: 'c9df6b2f0b980a240ef4d936489446f0af8da51e99c2672fed693a97359be972'
